### ISSUE TITLE
Dashboard carousel issue 

### ISSUE THREAD

**Issue by temp0065** [temp0065/mtm6201_final#1]
@abhaysharma 

I am trying to add auto playing carousel menus to my dashboard, but they don't seem to be functioning and aren't playing.

**Comment by abhaysharma** [comment]
@temp0065  it seems that you have fixed this issue.

**Comment by temp0065** [comment]
@abhaysharma

It still doesn't work for me. I think you may have mistook it for the working carousel on the homepage. I meant the carousels I added for the issues and doors + lights widgets; these ones are not functioning.

**Comment by abhaysharma** [comment]
@temp0065 you are missing the bootstrap script tag from the dashboard page. Second, you need to have unique ID values for your carousels, and update any related information accordingly.
